window.LI_TANGO_PUZZLES = [
  {
    "n": 620,
    "grid": [
      [
        ".",
        ".",
        ".",
        ".",
        ".",
        "."
      ],
      [
        ".",
        ".",
        ".",
        ".",
        ".",
        "."
      ],
      [
        ".",
        ".",
        ".",
        ".",
        ".",
        "."
      ],
      [
        "M",
        "S",
        "S",
        ".",
        ".",
        "."
      ],
      [
        ".",
        ".",
        "M",
        ".",
        ".",
        "."
      ],
      [
        ".",
        ".",
        "S",
        "S",
        "M",
        "M"
      ]
    ],
    "givens": [
      [false,false,false,false,false,false],
      [false,false,false,false,false,false],
      [false,false,false,false,false,false],
      [true,true,true,false,false,false],
      [false,false,true,false,false,false],
      [false,false,true,true,true,true]
    ],
    "signs": [
      {"r":1,"c":1,"d":"h","sign":"="},
      {"r":1,"c":2,"d":"h","sign":"×"},
      {"r":1,"c":3,"d":"h","sign":"="},
      {"r":1,"c":4,"d":"v","sign":"="},
      {"r":2,"c":4,"d":"v","sign":"×"},
      {"r":3,"c":4,"d":"h","sign":"×"},
      {"r":3,"c":5,"d":"h","sign":"×"}
    ],
    "givenCount":8,
    "signCount":7
  },
  {"n":621,"grid":[[".",".",".",".",".","."],["M",".",".",".",".","."],["M","S",".",".",".","."],["S","S",".",".",".","."],["M",".",".",".",".","."],[".",".",".",".",".","."]],"givens":[[false,false,false,false,false,false],[true,false,false,false,false,false],[true,true,false,false,false,false],[true,true,false,false,false,false],[true,false,false,false,false,false],[false,false,false,false,false,false]],"signs":[{"r":2,"c":5,"d":"v","sign":"="},{"r":3,"c":6,"d":"v","sign":"="},{"r":4,"c":5,"d":"v","sign":"="}],"givenCount":6,"signCount":3},
  {"n":622,"grid":[["M","M",".",".",".","."],["M","S","S",".",".","."],["S","S",".",".",".","."],[".",".",".",".",".","."],[".",".",".",".",".","."],[".",".",".",".",".","."]],"givens":[[true,true,false,false,false,false],[true,true,true,false,false,false],[true,true,false,false,false,false],[false,false,false,false,false,false],[false,false,false,false,false,false],[false,false,false,false,false,false]],"signs":[{"r":4,"c":5,"d":"v","sign":"×"},{"r":4,"c":6,"d":"v","sign":"×"},{"r":5,"c":4,"d":"h","sign":"="},{"r":5,"c":5,"d":"v","sign":"="},{"r":5,"c":6,"d":"v","sign":"="}],"givenCount":7,"signCount":5},
  {"n":623,"grid":[[".",".",".",".",".","."],[".","M",".",".","M","."],[".","M","M",".","M","."],[".","S",".","M","S","."],[".","M",".",".","M","."],[".",".",".",".",".","."]],"givens":[[false,false,false,false,false,false],[false,true,false,false,true,false],[false,true,true,false,true,false],[false,true,false,true,true,false],[false,true,false,false,true,false],[false,false,false,false,false,false]],"signs":[{"r":2,"c":3,"d":"h","sign":"×"},{"r":2,"c":4,"d":"v","sign":"="},{"r":4,"c":3,"d":"v","sign":"×"},{"r":5,"c":3,"d":"h","sign":"×"}],"givenCount":10,"signCount":4},
  {"n":624,"grid":[["M","M","S",".",".","."],[".",".",".",".",".","."],["M","S","M",".",".","."],[".",".",".","S","M","M"],[".",".",".",".",".","."],[".",".",".","M","M","S"]],"givens":[[true,true,true,false,false,false],[false,false,false,false,false,false],[true,true,true,false,false,false],[false,false,false,true,true,true],[false,false,false,false,false,false],[false,false,false,true,true,true]],"signs":[{"r":2,"c":1,"d":"h","sign":"×"},{"r":2,"c":2,"d":"h","sign":"="},{"r":5,"c":4,"d":"h","sign":"×"},{"r":5,"c":5,"d":"h","sign":"×"}],"givenCount":12,"signCount":4},
  {"n":625,"grid":[[".","M","M",".",".","."],[".","S","S",".",".","."],[".","M","M",".",".","."],[".","M",".",".",".","."],[".",".",".",".",".","."],[".",".",".",".",".","."]],"givens":[[false,true,true,false,false,false],[false,true,true,false,false,false],[false,true,true,false,false,false],[false,true,false,false,false,false],[false,false,false,false,false,false],[false,false,false,false,false,false]],"signs":[{"r":3,"c":5,"d":"v","sign":"="},{"r":4,"c":4,"d":"h","sign":"="},{"r":5,"c":4,"d":"v","sign":"="},{"r":5,"c":5,"d":"v","sign":"="}],"givenCount":7,"signCount":4},
  {"n":626,"grid":[[".",".",".",".",".","."],[".",".",".",".",".","."],[".",".",".",".",".","."],[".",".",".",".",".","."],[".","S","S",".","M","S"],[".","S","M",".","S","M"]],"givens":[[false,false,false,false,false,false],[false,false,false,false,false,false],[false,false,false,false,false,false],[false,false,false,false,false,false],[false,true,true,false,true,true],[false,true,true,false,true,true]],"signs":[{"r":1,"c":1,"d":"h","sign":"="},{"r":1,"c":2,"d":"v","sign":"×"},{"r":1,"c":4,"d":"h","sign":"×"},{"r":1,"c":5,"d":"v","sign":"="},{"r":2,"c":1,"d":"h","sign":"×"},{"r":2,"c":4,"d":"h","sign":"×"}],"givenCount":8,"signCount":6},
  {"n":628,"grid":[[".","M",".","M",".","."],["M",".","S",".",".","."],[".","S",".",".",".","."],["S",".",".",".",".","."],[".",".",".",".",".","."],[".",".",".",".",".","."]],"givens":[[false,true,false,true,false,false],[true,false,true,false,false,false],[false,true,false,false,false,false],[true,false,false,false,false,false],[false,false,false,false,false,false],[false,false,false,false,false,false]],"signs":[{"r":3,"c":6,"d":"v","sign":"×"},{"r":4,"c":5,"d":"v","sign":"×"},{"r":5,"c":4,"d":"h","sign":"="},{"r":5,"c":6,"d":"v","sign":"="},{"r":6,"c":3,"d":"h","sign":"="},{"r":6,"c":5,"d":"h","sign":"×"}],"givenCount":6,"signCount":6},
  {"n":629,"grid":[["M",".",".",".",".","."],[".","M",".",".",".","."],[".",".","M",".",".","."],[".",".",".","M",".","."],[".",".",".",".","M","."],[".",".",".",".",".","S"]],"givens":[[true,false,false,false,false,false],[false,true,false,false,false,false],[false,false,true,false,false,false],[false,false,false,true,false,false],[false,false,false,false,true,false],[false,false,false,false,false,true]],"signs":[{"r":1,"c":5,"d":"h","sign":"×"},{"r":2,"c":6,"d":"v","sign":"="},{"r":3,"c":5,"d":"v","sign":"×"},{"r":5,"c":1,"d":"v","sign":"="},{"r":5,"c":3,"d":"h","sign":"×"},{"r":6,"c":2,"d":"h","sign":"×"}],"givenCount":6,"signCount":6},
  {"n":630,"grid":[[".",".",".",".",".","."],[".","S","S",".",".","."],[".","S","M",".",".","."],[".",".",".","S","S","."],[".",".",".","S","M","."],[".",".",".",".",".","."]],"givens":[[false,false,false,false,false,false],[false,true,true,false,false,false],[false,true,true,false,false,false],[false,false,false,true,true,false],[false,false,false,true,true,false],[false,false,false,false,false,false]],"signs":[{"r":1,"c":1,"d":"v","sign":"×"},{"r":1,"c":2,"d":"h","sign":"="},{"r":1,"c":4,"d":"v","sign":"×"},{"r":3,"c":1,"d":"v","sign":"="},{"r":3,"c":4,"d":"h","sign":"×"},{"r":3,"c":6,"d":"v","sign":"="},{"r":4,"c":2,"d":"h","sign":"="},{"r":5,"c":3,"d":"v","sign":"="},{"r":5,"c":6,"d":"v","sign":"="},{"r":6,"c":4,"d":"h","sign":"="}],"givenCount":8,"signCount":10},
  {"n":631,"grid":[[".",".",".",".",".","."],[".",".",".",".",".","."],[".",".","S","M",".","."],[".",".","S","S",".","."],[".",".",".",".",".","."],[".",".",".",".",".","."]],"givens":[[false,false,false,false,false,false],[false,false,false,false,false,false],[false,false,true,true,false,false],[false,false,true,true,false,false],[false,false,false,false,false,false],[false,false,false,false,false,false]],"signs":[{"r":1,"c":3,"d":"h","sign":"×"},{"r":2,"c":3,"d":"h","sign":"="},{"r":3,"c":1,"d":"v","sign":"="},{"r":3,"c":2,"d":"v","sign":"×"},{"r":3,"c":5,"d":"v","sign":"="},{"r":3,"c":6,"d":"v","sign":"="},{"r":5,"c":3,"d":"h","sign":"="},{"r":6,"c":3,"d":"h","sign":"="}],"givenCount":4,"signCount":8},
  {"n":633,"grid":[["M","M",".",".",".","."],[".","M",".",".",".","."],["M","S",".",".",".","."],["M",".",".",".",".","."],["S","M",".",".",".","."],[".",".",".",".",".","."]],"givens":[[true,true,false,false,false,false],[false,true,false,false,false,false],[true,true,false,false,false,false],[true,false,false,false,false,false],[true,true,false,false,false,false],[false,false,false,false,false,false]],"signs":[{"r":2,"c":5,"d":"h","sign":"="},{"r":2,"c":6,"d":"v","sign":"="},{"r":3,"c":6,"d":"v","sign":"×"},{"r":4,"c":5,"d":"h","sign":"="},{"r":5,"c":5,"d":"v","sign":"="},{"r":6,"c":5,"d":"h","sign":"="}],"givenCount":8,"signCount":6},
  {"n":634,"grid":[[".","S","M","S",".","."],["S","M",".",".",".","."],[".",".",".",".",".","."],[".",".",".",".",".","."],[".",".",".",".","S","M"],[".",".","S","S","M","."]],"givens":[[false,true,true,true,false,false],[true,true,false,false,false,false],[false,false,false,false,false,false],[false,false,false,false,false,false],[false,false,false,false,true,true],[false,false,true,true,true,false]],"signs":[{"r":1,"c":6,"d":"v","sign":"×"},{"r":2,"c":5,"d":"h","sign":"×"},{"r":4,"c":2,"d":"v","sign":"="},{"r":5,"c":1,"d":"h","sign":"×"}],"givenCount":10,"signCount":4},
  {"n":635,"grid":[["S",".",".",".",".","."],["S",".","S",".",".","."],["M","M","S",".",".","."],[".",".","M",".",".","."],[".",".",".",".",".","."],[".",".",".",".",".","."]],"givens":[[true,false,false,false,false,false],[true,false,true,false,false,false],[true,true,true,false,false,false],[false,false,true,false,false,false],[false,false,false,false,false,false],[false,false,false,false,false,false]],"signs":[{"r":1,"c":5,"d":"h","sign":"×"},{"r":3,"c":4,"d":"v","sign":"="},{"r":4,"c":4,"d":"v","sign":"×"},{"r":4,"c":6,"d":"v","sign":"="},{"r":5,"c":4,"d":"h","sign":"×"},{"r":5,"c":6,"d":"v","sign":"×"},{"r":6,"c":1,"d":"h","sign":"="}],"givenCount":7,"signCount":7},
  {"n":636,"grid":[["M","M",".",".",".","."],["M","S","M",".",".","."],[".","S",".",".",".","."],[".",".",".",".",".","."],[".",".",".",".",".","."],[".",".",".",".",".","."]],"givens":[[true,true,false,false,false,false],[true,true,true,false,false,false],[false,true,false,false,false,false],[false,false,false,false,false,false],[false,false,false,false,false,false],[false,false,false,false,false,false]],"signs":[{"r":4,"c":5,"d":"v","sign":"×"},{"r":5,"c":4,"d":"h","sign":"="},{"r":5,"c":5,"d":"h","sign":"×"},{"r":5,"c":6,"d":"v","sign":"×"},{"r":6,"c":5,"d":"h","sign":"="}],"givenCount":6,"signCount":5},
  {"n":637,"grid":[[".",".",".",".",".","."],[".",".",".","M",".","."],[".","S","S",".",".","."],[".",".",".","S","S","."],[".",".","M",".",".","."],[".",".",".",".",".","."]],"givens":[[false,false,false,false,false,false],[false,false,false,true,false,false],[false,true,true,false,false,false],[false,false,false,true,true,false],[false,false,true,false,false,false],[false,false,false,false,false,false]],"signs":[{"r":2,"c":2,"d":"h","sign":"×"},{"r":2,"c":5,"d":"v","sign":"="},{"r":4,"c":2,"d":"v","sign":"="},{"r":5,"c":4,"d":"h","sign":"="}],"givenCount":6,"signCount":4},
  {"n":638,"grid":[[".",".","M","S",".","."],[".","M","S","M",".","."],["M","S","M","S",".","."],["S","M","S",".",".","."],[".",".",".",".",".","."],[".",".",".",".",".","."]],"givens":[[false,false,true,true,false,false],[false,true,true,true,false,false],[true,true,true,true,false,false],[true,true,true,false,false,false],[false,false,false,false,false,false],[false,false,false,false,false,false]],"signs":[{"r":4,"c":4,"d":"h","sign":"="},{"r":5,"c":5,"d":"h","sign":"="},{"r":5,"c":6,"d":"v","sign":"="},{"r":6,"c":5,"d":"h","sign":"×"}],"givenCount":12,"signCount":4}
];
